# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("employee.proto", :syntax => :proto3) do
    add_message "helloworld.EmployeeReq" do
      optional :id, :uint32, 1
    end
    add_message "helloworld.EmployeeRes" do
      optional :employeeId, :uint32, 1
    end
  end
end

module Helloworld
  EmployeeReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.EmployeeReq").msgclass
  EmployeeRes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.EmployeeRes").msgclass
end
