// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package helloworld;

public interface EmployeeResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.EmployeeRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 employeeId = 1;</code>
   */
  int getEmployeeId();
}
