// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package helloworld;

public final class EmployeeOuterClass {
  private EmployeeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_EmployeeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_EmployeeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_EmployeeRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_EmployeeRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\022\nhelloworld\"\031\n\013Employee" +
      "Req\022\n\n\002id\030\001 \001(\r\"!\n\013EmployeeRes\022\022\n\nemploy" +
      "eeId\030\001 \001(\r2N\n\010Employee\022B\n\014get_employee\022\027" +
      ".helloworld.EmployeeReq\032\027.helloworld.Emp" +
      "loyeeRes\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_EmployeeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_EmployeeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_EmployeeReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_helloworld_EmployeeRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_EmployeeRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_EmployeeRes_descriptor,
        new java.lang.String[] { "EmployeeId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
