// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package helloworld;

public interface EmployeeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.EmployeeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   */
  int getId();
}
